<a href="https://colab.research.google.com/github/MathewBiddle/sandbox/blob/main/notebooks/ERDDAP_data_access.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
!pip install erddapy

Requirement already satisfied: erddapy in /usr/local/lib/python3.11/dist-packages (2.2.4)
Requirement already satisfied: httpx>=0.25.0 in /usr/local/lib/python3.11/dist-packages (from erddapy) (0.28.1)
Requirement already satisfied: pandas<3,>=0.25.2 in /usr/local/lib/python3.11/dist-packages (from erddapy) (2.2.2)
Requirement already satisfied: pytz in /usr/local/lib/python3.11/dist-packages (from erddapy) (2025.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx>=0.25.0->erddapy) (4.9.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx>=0.25.0->erddapy) (2025.1.31)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx>=0.25.0->erddapy) (1.0.8)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from httpx>=0.25.0->erddapy) (3.10)
Requirement already satisfied: h11<0.15,>=0.13 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx>=0.25.0->erddapy) (0.14.0)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas<3,>=0.25.2->erddapy) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas<3,>=0.25.2->erddapy) (2.8.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas<3,>=0.25.2->erddapy) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=0.25.2->erddapy) (1.17.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx>=0.25.0->erddapy) (1.3.1)
Requirement already satisfied: typing_extensions>=4.5 in /usr/local/lib/python3.11/dist-packages (from anyio->httpx>=0.25.0->erddapy) (4.13.2)

In [13]:
from erddapy import ERDDAP
import pandas as pd

In [14]:
from erddapy import servers

gov_servers = {k: v.url for k, v in servers.items() if '.gov' in v.url}

In [15]:
df_out = pd.DataFrame()

for s, url in gov_servers.items():

    e = ERDDAP(server=url, protocol="tabledap")
    e.dataset_id = "allDatasets"

    e.variables = [
     "datasetID",
     "institution",
     "title",
      ]

    url = e.get_download_url(response="html")
    print(url)

    try:
      df = e.to_pandas(
      #index_col="datasetID",
      ).dropna()
      df['server'] = url
    except:
      print(f'{url} broken!')
      continue

    df_out = pd.concat([df_out,df], ignore_index=True)

https://coastwatch.pfeg.noaa.gov/erddap/tabledap/allDatasets.html?datasetID,institution,title
https://www.ncei.noaa.gov/erddap/tabledap/allDatasets.html?datasetID,institution,title
https://cwcgom.aoml.noaa.gov/erddap/tabledap/allDatasets.html?datasetID,institution,title
http://osmc.noaa.gov/erddap/tabledap/allDatasets.html?datasetID,institution,title
https://opendap.co-ops.nos.noaa.gov/erddap/tabledap/allDatasets.html?datasetID,institution,title
https://coastwatch.glerl.noaa.gov/erddap/tabledap/allDatasets.html?datasetID,institution,title
https://coastwatch.glerl.noaa.gov/erddap/tabledap/allDatasets.html?datasetID,institution,title broken!
https://upwell.pfeg.noaa.gov/erddap/tabledap/allDatasets.html?datasetID,institution,title
https://ferret.pmel.noaa.gov/pmel/erddap/tabledap/allDatasets.html?datasetID,institution,title
https://ferret.pmel.noaa.gov/alamo/erddap/tabledap/allDatasets.html?datasetID,institution,title
https://ferret.pmel.noaa.gov/socat/erddap/tabledap/allDatasets.html?datasetID,institution,title
https://polarwatch.noaa.gov/erddap/tabledap/allDatasets.html?datasetID,institution,title
https://erddap.incois.gov.in/erddap/tabledap/allDatasets.html?datasetID,institution,title
https://erddap.incois.gov.in/erddap/tabledap/allDatasets.html?datasetID,institution,title broken!
https://pub-data.diver.orr.noaa.gov/erddap/tabledap/allDatasets.html?datasetID,institution,title
https://coastwatch.noaa.gov/erddap/tabledap/allDatasets.html?datasetID,institution,title
https://oceanview.pfeg.noaa.gov/erddap/index.html/tabledap/allDatasets.html?datasetID,institution,title
https://oceanview.pfeg.noaa.gov/erddap/index.html/tabledap/allDatasets.html?datasetID,institution,title broken!

In [41]:
df_out['server_dset_combined'] = df_out['server']+ df_out['datasetID']

df_out['dset_url'] = df_out['server_dset_combined'].str.replace('allDatasets.html?datasetID,institution,title','',regex=False)

df_out.drop(columns=['server_dset_combined'], inplace=True)

df_out.iloc[0].T

datasetID                                            allDatasets
institution      NOAA NMFS SWFSC Environmental Research Division
title          * The List of All Active Datasets in this ERDD...
server         https://coastwatch.pfeg.noaa.gov/erddap/tabled...
dset_url       https://coastwatch.pfeg.noaa.gov/erddap/tabled...
Name: 0, dtype: object

In [42]:
df_out.loc[df_out['datasetID']!="allDatasets"] # remove allDatasets entries

,datasetID,institution,title,server,dset_url
1,nodcPJJU,NOAA OAR AOML,AN EXPERIMENTAL DATASET: Underway Sea Surface ...,https://coastwatch.pfeg.noaa.gov/erddap/tabled...,https://coastwatch.pfeg.noaa.gov/erddap/tabled...
2,ECMM_Atlantic_spotted_dolphin,Duke University Marine Geospatial Ecology Labo...,Atlantic Spotted Dolphin Habitat-based Marine ...,https://coastwatch.pfeg.noaa.gov/erddap/tabled...,https://coastwatch.pfeg.noaa.gov/erddap/tabled...
3,ECMM_Atlantic_white_sided_dolphin,Duke University Marine Geospatial Ecology Labo...,Atlantic White Sided Dolphin Habitat-based Mar...,https://coastwatch.pfeg.noaa.gov/erddap/tabled...,https://coastwatch.pfeg.noaa.gov/erddap/tabled...
4,testGridWav,???,Audio data from a local source.,https://coastwatch.pfeg.noaa.gov/erddap/tabled...,https://coastwatch.pfeg.noaa.gov/erddap/tabled...
5,testTableWav,???,Audio data from a local source.,https://coastwatch.pfeg.noaa.gov/erddap/tabled...,https://coastwatch.pfeg.noaa.gov/erddap/tabled...
...,...,...,...,...,...
14178,noaacwNPPN20S3AspmSCIDINEOFDaily,NOAA NESDIS STAR,Suspended Particulate Matter (Gap-filled DINEO...,https://coastwatch.noaa.gov/erddap/tabledap/al...,https://coastwatch.noaa.gov/erddap/tabledap/no...
14179,s3_nccos_d797_7ec9_e079,Copernicus Program,"zChlorophyll-a, Sentinel-3 experimental produc...",https://coastwatch.noaa.gov/erddap/tabledap/al...,https://coastwatch.noaa.gov/erddap/tabledap/s3...
14180,noaacwSpecialProject1,Copernicus Program,ZZ Special Project Copernicus Program S-3A OLC...,https://coastwatch.noaa.gov/erddap/tabledap/al...,https://coastwatch.noaa.gov/erddap/tabledap/no...
14181,noaacwSpecialProject,Copernicus Program,ZZ Special Project Copernicus Program S-3A+B O...,https://coastwatch.noaa.gov/erddap/tabledap/al...,https://coastwatch.noaa.gov/erddap/tabledap/no...
14182,noaacwSpecialProject2,Copernicus Program,ZZ Special Project Copernicus Program S-3B OLC...,https://coastwatch.noaa.gov/erddap/tabledap/al...,https://coastwatch.noaa.gov/erddap/tabledap/no...

In [43]:
df_out.loc[df_out['datasetID']!="allDatasets"].to_csv('gov_erddap_datasets.csv',index=False)